services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - back-tier

  # MONGO-DB
  db-mongo:
    image: mongo:latest
    container_name: db-mongo
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=admin
    networks:
      - back-tier
    ports:
      - "27017:27017"


networks:
  back-tier:

volumes:
  mongo-data:
